### ISSUE TITLE
store 应该没有被回收

### ISSUE THREAD

**Issue by falstack** [lincenying/mmf-blog-vue2-ssr#10]
这个写法应该是错的：
``` javascript
const state: {
  test: []
}

const mutations = {
  push_test (state, data) {
    if (test.length) {
      console.log('输出这一句证明有Bug')
    } else {
      state.test = data // Array
    }
  }
}
```

**Comment by lincenying** [comment]
页面没刷新, 只是路由变化, state肯定不会被回收, 不然vuex就没有办法处理所有组件的状态

**Comment by falstack** [comment]
``` javascript
const state: {
  user: null
}

const mutations = {
  push_test (state, data) {
    if (state.user) {
      console.log('输出这一句证明有Bug')
    } else {
      state.user = data // Array
    }
  }
}
```

如果这里要 set 的是 user，那么 user 与 user 之间就不是隔离开的

**Comment by lincenying** [comment]
第一次commit push_test 肯定是不会执行console的, 第二次commit push_test, 执行console不是很正常吗.

**Comment by falstack** [comment]
第一次的确不会，但这代表着，假设我有 N 多个 store 需要在服务端存储，那么除了第一次的请求外，其它的请求 ctx 都会带着这 N 个 store，请求结束时 ctx 是 2*N，我感觉这是有问题的。
并且在最近的一个项目中，一旦并发量高了之后，这个 store 会混乱，也就是说 user_1 也许会变成 user_2。
我观察了 Nuxt.js 的行为，发现它 runInNewContext = false 并且每次请求时，store 都会是空值。但是我没有从源码中找到原因，也许你可以帮我一下？
（我认为这个问题是比较严重的）

**Comment by lincenying** [comment]
本仓库的代码, 并没有设置runInNewContext, 也就是默认的true, 因此每个用户都是一个独立的上下文, 何来数据乱窜
另外store的数据, 只有第一次请求, 把所有所需的数据写到里面, 然后输出到html文件给浏览器端作为初始数据, 后面在不刷新的情况下, 所有的操作都是走浏览器端的store, 和node端的ctx有什么关系?

如果要用ssr, 建议先认真看看官方文档:  https://ssr.vuejs.org/zh/

**Comment by lincenying** [comment]
runInNewContext 设置为 false 的写法:   https://github.com/lincenying/mmf-blog-vue2-pwa-ssr/

**Comment by falstack** [comment]
我发现我上面的表述不清楚，并且我的确忽略了一些问题。

这个项目的 runInNewContext = true，这是我没有注意到的，的确，当 runInNewContext = true 的时候，无论你的 state 怎么写，都不会导致状态出问题

我上面说的所有，都是当 runInNewContext = false 时的情况

事实上，经过我的测试，即使 runInNewContext = false，时你使用下面的写法，也会使状态出些问题。
``` javascript
const state = () => ({
  user: null
})
```
当 user-1 发请求的时候，user 的确是 null，而当 user-2 发请求的时候，user 就不再是 null，而是 user-1

这是我遇到的一个麻烦，的确与这个项目无关，我在这里提出来只是想看看你有没有办法解决这个问题，因为我找不到其它 vue-ssr 更好的应用实例了

另外，我发现 Nuxt.js 的 state 写法就是上面的写法，但每次请求的时候，user 都是 null，并且 runInNewContext = false

你有专门的 vue-ssr 交流群吗？即使在 github 上我也很难搜到有用的 SSR 实例来参考
