### ISSUE TITLE
你好，我想请问下admin这个入口怎么在ssr项目中配置呢

### ISSUE THREAD

**Issue by shx1545** [lincenying/mmf-blog-vue2-ssr#11]
如题，有没有demo，或者截个图也行。谢谢了。

**Comment by lincenying** [comment]
你是想把admin入口也放到ssr里去还是什么意思?

**Comment by shx1545** [comment]
是的，因为我的项目也是想让，前台采用 SSR 模式渲染, 后台采用 SPA 模式

**Comment by lincenying** [comment]
这个项目本来就是前台ssr, 后台spa啊...

**Comment by shx1545** [comment]
我知道，我是说想放到一起，肯定需要再ssr项目中进行配置

**Comment by shx1545** [comment]
![image](https://user-images.githubusercontent.com/29303050/34096551-b13621c8-e410-11e7-8804-70d34cbfc79d.png)

**Comment by lincenying** [comment]
vue应该没有这个能根据路由来决定是不是服务端渲染的功能, 只能是1个入口要么ssr, 要么spa, 没看到vue文档有这方面的说明

**Comment by lincenying** [comment]
或者可能可以通过node层来判断决定, 但是觉得没多大意义, 还不如分开

**Comment by shx1545** [comment]
但是好像你这个admin.js是后台入口

**Comment by lincenying** [comment]
入口不打紧, 主要是路由, 路由合并到一个文件就行了

然后在server.js里决定是用ssr渲染还是直接渲染模板
