### ISSUE TITLE
无法打开8080

### ISSUE THREAD

**Issue by yiqianglin** [lincenying/mmf-blog-vue2-ssr#15]
浏览器访问的时候，出现
![image](https://user-images.githubusercontent.com/15794229/46601775-cd62db00-cb20-11e8-9c08-070e813deeaa.png)

**Comment by yiqianglin** [comment]
![image](https://user-images.githubusercontent.com/15794229/46601973-6f82c300-cb21-11e8-94f3-38e41abac72b.png)
添加管理员的时候，一直在loading。没有响应

**Comment by lincenying** [comment]
你node请求中的header里带有中文, 看下是不是cookies里有中文内容
