### ISSUE TITLE
ssr文章页刷新不能获取DOM

### ISSUE THREAD

**Issue by SoulFlys** [lincenying/mmf-blog-vue2-ssr#4]
ssr  run start  在文章页的时候刷新不能获取匹配的组件内容

**Comment by lincenying** [comment]
什么意思~?

**Comment by SoulFlys** [comment]
就是在文章页  F5刷新的时候  数据读出来了 但是没有匹配到对应的路由 页面空白了

**Comment by lincenying** [comment]
改动过代码吗?

**Comment by SoulFlys** [comment]
我参照尤大的项目  基本上没有改动什么代码 但是当我启动服务的时候 我直接进入文章页面 页面空白的 就是在文章页 无法刷新 刷新就无法匹配到文章页

**Comment by lincenying** [comment]
你可以把代码从先git clone, 不改任何代码试下看...
这样我没有代码,也没有错误信息, 很难排查原因.

**Comment by SoulFlys** [comment]
好的，我再试试，谢谢你~

**Comment by SoulFlys** [comment]
博主 我还有个问题想问一下 为什么我的请求在生产环境下 F12还能看到

**Comment by lincenying** [comment]
ajax请求? 还是什么请求...

**Comment by SoulFlys** [comment]
ajax请求

**Comment by lincenying** [comment]
只要是在浏览器里, ajax请求都能在 network 里看到.

**Comment by SoulFlys** [comment]
额 好吧

**Comment by SoulFlys** [comment]
不好意思咩，还有问题想问下您，怎么样确保在beforeMount中store.dispatch('a')后，mounted中一定能拿到store.dispatch('a')之后a的数据了，貌似是因为异步的问题，这里不是很明白，还请多多指教~

**Comment by lincenying** [comment]
没有办法保证, 只能在watch中加监控

**Comment by SoulFlys** [comment]
我检查了下我的server.js和server_entery.js几乎和你的一样，但是为什么你进入路由之后 一定是等数据获取完才渲染页面，而我的就会出现先渲染页面再获取数据呢

**Comment by lincenying** [comment]
我并没有这么设置, 可能的原因是   1, 动画效果  2,  我有用vuex做缓存 3, 你接口速度太慢
