### ISSUE TITLE
如何按需进行数据的预取？

### ISSUE THREAD

**Issue by wmui** [lincenying/mmf-blog-vue2-ssr#8]
朋友，又来打扰你了。最近在看你这个项目时遇到了一个问题，我观察到预取数据`window.__INITIAL_STATE__`中，在列表页查看源代码，详情页即`item:{"data":{}}`为空，在详情页查看源代码，列表页即`"frontend":{"article":{"lists":{"data":[],"hasNext":0,"page":1,"path":""}`为空，成功做到了按页面所需进行预取数据，然而`entry-server.js`在中，` context.state = store.state`，长下文会预取所有state数据，所以我想问下你是如何做到数据按需预取的，谢谢

**Comment by lincenying** [comment]
每个路由组件里, 都有这个prefetch对象函数(官网实例可能不是叫这个名称), 
https://github.com/lincenying/mmf-blog-vue2-ssr/blob/master/src/pages/frontend-index.vue#L39
然后在entry-server的
https://github.com/lincenying/mmf-blog-vue2-ssr/blob/master/src/entry-server.js#L29-L31里, 会读取当前路由所有匹配的组件, 再依次去查找这个函数, 如果发现, 就会执行这个函数发起请求, 然后把数据给store, 所以是不会加载多余数据的

一般的做法是, 在路由组件, 加载当前路由所需要的所有数据, 再通过props传给子组件.

**Comment by lincenying** [comment]
官网实例用的是 asyncData, 只是名称不一样而已, 做法是完全一致的

https://github.com/lincenying/mmf-blog-vue2-pwa-ssr/blob/master/src/pages/frontend-index.vue#L29-L36

https://github.com/lincenying/mmf-blog-vue2-pwa-ssr/blob/master/src/entry-server.js#L43-L49

**Comment by wmui** [comment]
@lincenying 我大概明白了你的意思，举例来说，当你进入列表页，store中根据async函数获取并存储了列表数据，然后被添加到`window.__INITIAL_STATE__`中。但是当你从列表页进入文章详情页，store中的列表页数据还存在，所以在详情页的`window.__INITIAL_STATE__`中不是还有列表数据吗，为什么你的确是空的？

**Comment by lincenying** [comment]
直接打开详情页和从列表页点过去是不一样的, 
直接打开, 是肯定不会加载列表的数据的 
点击过去, 因为之前列表的数据已经加载了, 而点击过去, 是走客户端处理的, 是不会再从node层去请求详情页数据的.

**Comment by wmui** [comment]
感谢，问题顺利解决
